# permissions for end users to view restapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: restapi-viewer-role
rules:
- apiGroups:
  - webapp.mydev.org
  resources:
  - restapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.mydev.org
  resources:
  - restapis/status
  verbs:
  - get
